// @vitest-environment node
import { randomUUID } from 'node:crypto'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import type { CandidateInterviewQuestion, ExperienceInput } from '@shared'
import { nativeSqliteAvailable, openTestRepository, type TestRepositoryHandle } from './store-test-repository'
import { defaultOperatorId, emptySchedule, seedConfirmedCase, seedImportedPerson } from './store-test-fixtures-business'

const context = { operatorId: defaultOperatorId, locale: 'zh-CN' as const, customer: { key: 'fixture', label: '客户' } }
const draft = {
  category: 'responsibility' as const,
  keyword: 'Java',
  text: '请说明 Java 项目中本人负责的设计。',
  scoringGuide: '确认本人职责与依据。',
  sourceQuote: '请说明 Java 项目中本人负责的设计。'
}

describe.skipIf(!nativeSqliteAvailable)('QuestionBankStore via EncryptedApplicationRepository', () => {
  let handle: TestRepositoryHandle
  beforeEach(() => {
    handle = openTestRepository()
  })
  afterEach(() => handle.dispose())

  /** Saves an interview question generated by an experience run, which queues it as a bank source. */
  const captureQuestion = (text = draft.text, operatorId = defaultOperatorId) => {
    const { repository } = handle
    const person = seedImportedPerson(repository)
    const job = seedConfirmedCase(repository)
    const pair = { documentId: person.documentId, reviewId: job.reviewId }
    const round = repository.advanceBusinessProgress(
      { ...pair, expectedRevision: 0, mutationId: randomUUID(), action: 'schedule', schedule: emptySchedule() },
      'HR'
    )
    const question: CandidateInterviewQuestion = {
      id: randomUUID(),
      text,
      selected: true,
      source: 'match',
      sourceLabel: 'Java',
      requirement: 'Java'
    }
    const input: ExperienceInput = {
      task: 'interview',
      context: { ...context, operatorId },
      requirements: [{ key: 'skills', label: '技术', value: 'Java' }],
      facts: [],
      projects: [],
      hardFilters: [],
      hrRules: [],
      previousQuestions: [],
      notes: '',
      locale: 'zh-CN'
    }
    const runId = repository.saveExperienceRun({
      ...pair,
      interviewId: round.progress!.rounds[0]!.id,
      profileVersion: person.profile!.version,
      jobCaseVersion: job.jobCase!.version,
      rulesRevision: 0,
      modelKey: 'fixture',
      input,
      output: [question],
      bundle: { task: 'interview', instructions: [], refs: [] }
    })
    repository.advanceBusinessProgress(
      {
        ...pair,
        expectedRevision: round.revision,
        mutationId: randomUUID(),
        action: 'prepare',
        roundNumber: 1,
        questions: [{ ...question, experienceRunId: runId }]
      },
      'HR'
    )
    return { runId, question }
  }

  it('turns a saved generated question into a bank entry once and lists it for its own scope', () => {
    const { repository } = handle
    const { runId, question } = captureQuestion()
    const [source] = repository.getPendingBankQuestions()
    expect(source).toMatchObject({ runId, questionId: question.id, text: question.text, requirement: 'Java', bankId: null })

    repository.saveQuestionTemplate(source!, draft)
    expect(repository.getPendingBankQuestions()).toHaveLength(0)
    // A replayed acceptance of an already analyzed source is ignored.
    repository.saveQuestionTemplate(source!, draft)
    const bank = handle.reopen().listQuestionBank()
    expect(bank).toHaveLength(1)
    expect(bank[0]).toMatchObject({ version: 1, text: draft.text, keyword: 'Java', sources: 1, enabled: true, state: 'available' })
    expect(handle.repository.listQuestionBank({ search: 'java' })).toHaveLength(1)
    expect(handle.repository.listQuestionBank({ search: '不存在的关键词' })).toHaveLength(0)
    expect(handle.repository.getApplicableBankQuestions([{ key: 'skills', label: '技术', value: 'Java' }], context)).toHaveLength(1)
    expect(
      handle.repository.getApplicableBankQuestions([{ key: 'skills', label: '技术', value: 'Java' }], {
        ...context,
        operatorId: randomUUID()
      })
    ).toHaveLength(0)
  })

  it('refuses to adopt, and does not queue, questions generated for another operator', () => {
    expect(() => captureQuestion(draft.text, '00000000-0000-4000-8000-000000000002')).toThrow(/其他用户|他の利用者/)
    expect(handle.repository.getPendingBankQuestions()).toHaveLength(0)
  })

  it('disables and re-enables entries only at the current version', () => {
    const { repository } = handle
    captureQuestion()
    repository.saveQuestionTemplate(repository.getPendingBankQuestions()[0]!, draft)
    const entry = repository.listQuestionBank()[0]!
    expect(() => repository.controlQuestionBank({ id: entry.id, expectedVersion: entry.version + 1, enabled: false })).toThrow(
      /题库已更新|質問集が更新/
    )

    const disabled = repository.controlQuestionBank({ id: entry.id, expectedVersion: entry.version, enabled: false })
    expect(disabled[0]).toMatchObject({ enabled: false, state: 'paused', locked: true, version: 2 })
    expect(repository.listQuestionBank()).toHaveLength(0)
    expect(() => repository.controlQuestionBank({ id: entry.id, expectedVersion: 1, enabled: true })).toThrow(/题库已更新|質問集が更新/)
    repository.controlQuestionBank({ id: entry.id, expectedVersion: 2, enabled: true })
    expect(handle.reopen().listQuestionBank()[0]).toMatchObject({ enabled: true, version: 3 })
  })

  it('refuses to restore a version that does not exist in history', () => {
    const { repository } = handle
    captureQuestion()
    repository.saveQuestionTemplate(repository.getPendingBankQuestions()[0]!, draft)
    const entry = repository.listQuestionBank()[0]!
    expect(repository.getQuestionBankHistory(entry.id)).toEqual([])
    expect(() => repository.restoreQuestionBankVersion(entry.id, entry.version, 1)).toThrow(/失效|無効/)
  })
})
